### ISSUE TITLE
Question about educat

### ISSUE THREAD

**Issue by yzhang104** [nsrr/shhs-data-dictionary#1104]
why is the level 2 defined as 11yr-15yr instead of 12yr (high school graduate/GED)-15yr? is it possible to derive the education variable using 12 yr (high school graduate) and 16 yr (college graduate) as cutoff values?

**Comment by mrueschman** [comment]
Unfortunately this appears to be the rawest form of the variable provided by the SHHS Coordinating Center. This is an A-variable, meaning it was requested from the parent cohort and each of them pulled/derived it based on their own source data. Maybe back in 1995 it was common to ask education as "number of years" (write a number) instead of the usual categories we see nowadays.

The only other notes I see in the documentation is that for those with a GED the "educat" variable was meant to be set to 12. And that years in tech school were counted like years in college.
